### ISSUE TITLE
ERC1400 Regular Definition

### ISSUE THREAD

**Issue by varunpareek690** [Poovarasi5603/ERC1400-SecurityTokenStandard#1]
Hi!
Just wanted to know how have you implemented ERC1400.. The one provided in the github repository of UniversalToken seems to have to many functions
How did you choose which is best for you and included KYC in this?
I am building a  token myself on it but am confused about the implementation?

**Comment by Brixbit** [comment]
In this project, I have utilised three sub-standards of the ERC-1400 security token :

ERC-1400: Core security token standard.
ERC-1594:  transfer restrictions for regulatory compliance.
ERC-1643: Facilitates off-chain data verification.

Instead of the standard ERC-20 transfer function, this implementation uses transferWithData, enabling restricted token transfers. KYC verification is integrated to validate users before transfers.

Depending on your requirements, you can choose additional ERC-1400 sub-standards for enhanced functionality.

**Comment by Poovarasi5603** [comment]
In this project, I have utilised three sub-standards of the ERC-1400 security token :

ERC-1400: Core security token standard.
ERC-1594: transfer restrictions for regulatory compliance.
ERC-1643: Facilitates off-chain data verification.

Instead of the standard ERC-20 transfer function, this implementation uses transferWithData, enabling restricted token transfers. KYC verification is integrated to validate users before transfers.

Depending on your requirements, you can choose additional ERC-1400 sub-standards for enhanced functionality.
